version: "3"
services:
    master1:
        image: mysql:8.0.19
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=master1
            - MYSQL_PASSWORD=master1
            - MYSQL_DATABASE=sample
        volumes:
            - ./docker/master1/data:/var/lib/mysql
            - ./docker/master1/my.cnf:/etc/mysql/conf.d/my.cnf
        ports:
            - 3306:3306
        networks:
            cluster_network:
                ipv4_address: 172.30.0.60

    slave1:
        image: mysql:8.0.19
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=slave1
            - MYSQL_PASSWORD=slave1
            - MYSQL_DATABASE=sample
        volumes:
            - ./docker/slave1/data:/var/lib/mysql
            - ./docker/slave1/my.cnf:/etc/mysql/conf.d/my.cnf
        ports:
            - 3308:3308
        networks:
            cluster_network:
                ipv4_address: 172.30.0.68

    slave2:
        image: mysql:8.0.19
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=slave2
            - MYSQL_PASSWORD=slave2
            - MYSQL_DATABASE=sample
        volumes:
            - ./docker/slave2/data:/var/lib/mysql
            - ./docker/slave2/my.cnf:/etc/mysql/conf.d/my.cnf
        ports:
            - 3309:3309
        networks:
            cluster_network:
                ipv4_address: 172.30.0.69
    
    router:
        image: mysql/mysql-router:8.0.19
        environment:
            - MYSQL_HOST=master1
            - MYSQL_PORT=3306
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - MYSQL_INNODB_CLUSTER_MEMBERS=3
        ports:
            - 6446:6446
        networks:
            cluster_network:
                ipv4_address: 172.30.1.60

networks:
    cluster_network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.30.0.0/16
